[book]
title = "ChIP-seq Analysis Tutorial "
authors = ["Raja Khan"]
language = "en"

[output.html]
additional-css = ["custom.css"]
additional-js = ["custom.js"]
[output.html.print]
enable = false







